// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Invalid CC', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Invalid CC', async function() {
    await driver.get("https://beyondblue--dev.lightning.force.com/lightning/r/Contact/0030l00000UedkOAAR/view?0.source=alohaHeader")
    await driver.findElement(By.linkText("Donate")).click()
    await driver.findElement(By.xpath("//lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//lightning-input/div/input")).sendKeys("3")
    await driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/div/input")).click()
    await driver.findElement(By.css("li:nth-child(1) .slds-media__body:nth-child(2) > .slds-lookup__result-text")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/div/lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/div/lightning-input/div/input")).sendKeys("4444444444444444")
    await driver.findElement(By.xpath("//div[3]/div/lightning-input/div/input")).click()
    await driver.findElement(By.xpath("//div[3]/div/lightning-input/div/input")).sendKeys("ddd")
    await driver.findElement(By.xpath("//select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//select"))
      await dropdown.findElement(By.css("*:nth-child(2)")).click()
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div/select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//div[2]/div/div/div/select"))
      await dropdown.findElement(By.css("*:nth-child(5)")).click()
    }
    await driver.findElement(By.xpath("//div[3]/lightning-input/div/input")).click()
    await driver.findElement(By.css(".slds-button_brand")).click()
    {
      const element = await driver.findElement(By.css(".slds-button_brand"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    assert(await driver.findElement(By.css(".slds-text-color_error")).getText() == "Card security code: The security code for this card is invalid. Please check the code and submit the payment again.")
  })
})
